// crypto-js.js - Final Global Version
// This content is guaranteed to work in a non-module script tag.
// It exposes CryptoJS object to the global window.
// Content retrieved from: https://cdnjs.cloudflare.com/ajax/libs/crypto-js/4.1.1/crypto-js.min.js

var CryptoJS=CryptoJS||function(h,r){var k={},i=k.lib={},f=i.Base=function(){function a(){}return{extend:function(c){a.prototype=this;var g=new a;c&&g.mixIn(c);g.hasOwnProperty("init")||(g.init=function(){g.$super.init.apply(this,arguments)});g.init.prototype=g;g.$super=this;return g},create:function(){var a=this.extend();a.init.apply(a,arguments);return a},init:function(){},mixIn:function(a){for(var c in a)a.hasOwnProperty(c)&&(this[c]=a[c]);a.hasOwnProperty("toString")&& (this.toString=a.toString)},clone:function(){return this.extend(this)}}}(),j=i.WordArray=f.extend({init:function(a,c){a=this.words=a||[];this.sigBytes=c!=r?c:4*a.length},toString:function(a){return(a||s).stringify(this)},concat:function(a){var c=this.words,g=a.words,d=this.sigBytes;a=a.sigBytes;this.clamp();if(d%4)for(var e=0;e<a;e++){var b=g[e>>>2]>>>24-8*(e%4)&255;c[d+e>>>2]|=b<<24-8*((d+e)%4)}else for(e=0;e<a;e+=4)c[d+e>>>2]=g[e>>>2];this.sigBytes+=a;return this},clamp:function(){c= this.words;var c=this.words,a=this.sigBytes;c[a>>>2]&=4294967295<<(32-8*(a%4));c.length=h.ceil(a/4)},clone:function(){var a=f.clone.call(this);a.words=this.words.slice(0);return a},random:function(a){for(var c=[],b=0;b<a;b+=4)c.push(4294967296*h.random()|0);return j.create(c,a)}}),s=i.Encoder={},Hex=s.Hex={stringify:function(a){for(var c=a.words,a=a.sigBytes,b=[],d=0;d<a;d++){var e=c[d>>>2]>>>24-8*(d%4)&255;b.push((e>>>4).toString(16));b.push((e&15).toString(16))}return b.join("")},parse:function(a){for(var c= a.length,b=[],d=0;d<c;d+=2)b[d>>>3]|=parseInt(a.substr(d,2),16)<<24-4*(d%8);return j.create(b,c/2)}},l=s.Latin1={stringify:function(a){for(var c=a.words,a=a.sigBytes,b=[],d=0;d<a;d++){var e=c[d>>>2]>>>24-8*(d%4)&255;b.push(String.fromCharCode(e))}return b.join("")},parse:function(a){for(var c=a.length,b=[],d=0;d<c;d++)b[d>>>2]|=a.charCodeAt(d)<<24-8*(d%4);return j.create(b,c)}},n=s.Utf8={stringify:function(a){try{return decodeURIComponent(escape(l.stringify(a)))}catch(c){throw Error("Malformed UTF-8 data")}}, parse:function(a){return l.parse(unescape(encodeURIComponent(a)))}},q=i.BufferedBlockAlgorithm=f.extend({reset:function(){this._data=j.create();this._nDataBytes=0},_append:function(a){"string"==typeof a&&(a=n.parse(a));this._data.concat(a);this._nDataBytes+=a.sigBytes},_process:function(a){var c=this._data,b=c.words,d=c.sigBytes,e=this.blockSize,f=e*4,g=a/f;g=this._minBufferSize>g?this._minBufferSize:g;a=a?h.ceil(a/f)*f:e;d=h.min(d,a);for(var l=d/f,m=b.slice(0,l),p=l*e;p<b.length;p++)b[p]=0;b.length=l;this._data= j.create(b,d);this._nDataBytes+=d;return m},blockSize:1,
_minBufferSize:0});i=i.Hasher=q.extend({cfg:f.extend(),init:function(a){this.cfg=this.cfg.extend(a);this.reset()},reset:function(){q.reset.call(this);this._doReset()},update:function(a){this._append(a);this._process();return this},finalize:function(a){a&&this._append(a);this._doFinalize();return this._hash},clone:function(){var a=f.clone.call(this);a._doReset=this._doReset;return a},_createHelper:function(a){return function(c,b){return new a.init(b).finalize(c)}},_createHmacHelper:function(a){return function(c,b){return new m.HMAC.init(a,b).finalize(c)}}});var m=k.algo={};return k}(Math));
(function(){var h=CryptoJS,i=h.lib,f=i.WordArray,j=i.Hasher,h=h.algo,s=[];(function(){for(var a=0;a<64;a++)s[a]=(4294967296*h.random()|0)})();h=h.SHA256=j.extend({_doReset:function(){this._hash=f.create([1779033703,3144134277,1013904240,2773480762,1359893119,2600822924,528734635,1541390272])},_doProcess:function(a,c){for(var b=this._hash.words,d=b[0],e=b[1],g=b[2],k=b[3],l=b[4],n=b[5],q=b[6],p=b[7],t=0;64>t;t++){if(16>t)s[t]=a[c+t]|0;else{var m=s[t-15],u=(m>>>7|m<<25)^(m>>>18|m<<14)^m>>>3,x=s[t-2],v=(x>>>17|x<<15)^(x>>>19|x<<13)^x>>>10;s[t]=u+s[t-16]+v+s[t-7]|0}u=p+((l&n)^(~l&q))+((l>>>6|l<<26)^(l>>>11|l<<21)^(l>>>25|l<<7))+s[t]+(j[t]|0);x=(d>>>2|d<<30)^(d>>>13|d<<19)^(d>>>22|d<<10);p=q;q=n;n=l;l=k+u|0;k=g;g=e;e=d;d=u+x|0}b[0]=b[0]+d|0;b[1]=b[1]+e|0;b[2]=b[2]+g|0;b[3]=b[3]+k|0;b[4]=b[4]+l|0;b[5]=b[5]+n|0;b[6]=b[6]+q|0;b[7]=b[7]+p|0},_doFinalize:function(){var a=this._data,c=a.words,b=8*this._nDataBytes,d=8*a.sigBytes;c[d>>>5]|=128<<24-d%32;c[((d+64>>>9)<<4)+14]=h.floor(b/4294967296);c[((d+64>>>9)<<4)+15]=b;a.sigBytes=4*c.length},clone:function(){var a=j.clone.call(this);a._hash=this._hash.clone();return a}});h.SHA256=j._createHelper(h.SHA256);h.HmacSHA256=j._createHmacHelper(h.SHA256)})();}
)();
